### ISSUE TITLE
German Language Defect

### ISSUE THREAD

**Issue by themediawatcher** [jasadams/imagezoom#10]
hi,
i am using imagezoom with a german firefox and windows. up to version 5.x everything was fine, but after updating to version 0.6 or 0.6.1, the german context menu appears in a language which i do not understand. it is neither english nor my local language, german.

inside the imagezoom.xpi, there is a chrome.manifest file and there is a german language information. "de chrome" which links to locale/de (which indeed seems to be the german language source, but there is also another one, named locale/eo and this is definitively not german language.

can you fix that please?

**Comment by jasadams** [comment]
Thanks for reporting and determining the cause of the bug, fixed in version 0.6.2 (already submitted to mozilla)

**Comment by themediawatcher** [comment]
Thanks for your quick reply. Unfortunately that did not fix the problem. the context menu does not show up at all after using version 0.6.2 ;-(

for my own testing purposes, i edited out the reference to the locale/eo thing in version 0.6.0 and ran into the same problems that the context menu now was totally gone and rightclickmouse/zoom-wheel didnt work any longer. ;-(

info: but the settings dialog within the addons-manager inside firefox now is correctly shown in german.

**Comment by jasadams** [comment]
ok, let me check, I will download the german version and actually test this time

**Comment by jasadams** [comment]
0.6.3 should do the trick

**Comment by themediawatcher** [comment]
Works like a charm! Thank you so much! Excellent. Thanks for your support.
